# Generated by Django 5.0.2 on 2024-03-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_appuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_pictures'),
        ),
    ]
