# Generated by Django 5.0.2 on 2024-03-19 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmembers',
            old_name='room',
            new_name='conversation',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='room',
            new_name='conversation',
        ),
    ]
