# Generated by Django 5.0.2 on 2026-05-19 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversation_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmembers',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.conversation'),
        ),
    ]
